@api = http://localhost:3000
@apiUsers=http://localhost:3000/users
@apiCardsByUser=http://localhost:4000/users/1/cards
@host300=http://localhost:3000

GET {{api}}/cards

###
POST {{api}}
Content-Type: application/json

{
    "apellido": "nasello",
"foto": "lautaro-nasello.jpg",
"id_equipo": 11,
"id_posicion": 2,
"id_rareza": 2,
"id_serie": 2,
"nombre": "lautaro"
}

###
DELETE {{api}}/20

### update

PUT {{api}}/22
Content-Type: application/json

{
    "nombre":"Carlos",
    "apellido":"Martines",
    "foto":"carlos_martinez.jpg",
    "id_rarezas":2,
    "id_posiciones":4,
    "id_equipos":50
}

###

GET {{apiUsers}}

###
POST {{apiUsers}}
Content-Type: application/json

{
    "usuario":"quique",
    "contrasena": "martines",
    "email":"quique_hernandez.jpg",
    "id_rol":2
}

###

DELETE {{apiUsers}}/1

###
GET {{apiCardsByUser}}

 